name: Test Action
run-name: Start By ${{ github.actor }}  
on: [push, workflow_dispatch]

jobs:
    Build:
        runs-on: ubuntu-latest
        name: Welcome
        steps:
            - name: Welcome Someone
              id: greet
              uses: alexdesouzasilva/actions@v1.3
              with:
                name: 'Alex De Souza Silva'
            - name: Get the output message
              run: echo "The message was ${{ steps.greet.outputs.message }}"

